syntax = "proto3";

package zmk.settings;

message ActivitySettings {
    uint32 idle_ms = 1;
    uint32 sleep_ms = 2;
    uint32 source = 3;
}

message GetActivitySettingsRequest {}
message GetActivitySettingsResponse { ActivitySettings settings = 1; }
message SetActivitySettingsRequest { ActivitySettings settings = 1; }
message SetActivitySettingsResponse { bool success = 1; }
message GetAllActivitySettingsRequest {}
message GetAllActivitySettingsResponse { bool request_sent = 1; }
message ActivitySettingsNotification { ActivitySettings settings = 1; }

message Request {
    oneof request_type {
        GetActivitySettingsRequest get_activity_settings = 1;
        SetActivitySettingsRequest set_activity_settings = 2;
        GetAllActivitySettingsRequest get_all_activity_settings = 3;
    }
}

message ErrorResponse { string message = 1; }

message Response {
    oneof response_type {
        ErrorResponse error = 1;
        GetActivitySettingsResponse get_activity_settings = 2;
        SetActivitySettingsResponse set_activity_settings = 3;
        GetAllActivitySettingsResponse get_all_activity_settings = 4;
    }
}

message Notification {
    oneof notification_type {
        ActivitySettingsNotification activity_settings = 1;
    }
}
