/* SPDX-License-Identifier: MIT */

#pragma once

#define ZMK_POWER_SETTINGS_IDLE_INC_CMD 0
#define ZMK_POWER_SETTINGS_IDLE_DEC_CMD 1
#define ZMK_POWER_SETTINGS_DEEP_SLEEP_INC_CMD 2
#define ZMK_POWER_SETTINGS_DEEP_SLEEP_DEC_CMD 3
